name: Automatisation des tests
on: push
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Compilation
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          make test
  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Test fonction add
        run: |
          ./build/src/calculator add 10 5
  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Test fonction sub
        run: |
          ./build/src/calculator sub 10 5

  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Test fonction Mul
        run: |
          ./build/src/calculator mul 10 5
    
  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Test fonction div
        run: |
          ./build/src/calculator div 10 5
  Test_Carre:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Test fonction carree
        run: |
          ./build/src/calculator car 5
  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Test_Add
      - Test_Carre
      - Compilation
      - Test_Div
      - Test_Mul
      - Test_Sub
    steps:
      - name: Déploiement
        run: echo "Déploiement de la solution"